// ==========================================================================
// ŠTOK I KRILO — arhiva vesti iz koda
//
// Do 5. 10. 2026. ovih 34 vesti stajalo je tvrdo upisano u index.html, uporedo
// sa vestima iz uredništva. Posledice su bile tri: stranica je svakom
// posetiocu učitavala šezdesetak kilobajta teksta i kad gleda samo cene, stara
// vest se nije mogla ispraviti kroz admin nego samo kroz kod, i dva niza se
// nisu mogla poređati po datumu, jer su tvrdo upisane nosile datum kao tekst
// („27. avg 2026"), a serverske ISO zapis.
//
// Ovaj fajl je prelaz: news-import.mjs ga jednom upiše u bazu uredništva, i
// posle toga ni on ni funkcija za uvoz nisu više potrebni.
//
// Šest vesti nema tačan dan, nego samo mesec ili godinu. Kod njih je polje
// datumTacan netačno, a datumISO nosi prvi dan razdoblja i služi samo za
// redosled. Prikazani datum ostaje onakav kakav je bio, jer dan koji se ne
// zna ne sme da se izmisli.
// ==========================================================================
export const VESTI_ARHIVA = 
[
  {
    "id": "arh-001",
    "cat": "trziste",
    "catLabel": "TRŽIŠTE",
    "date": "30. avg 2026",
    "title": "Britanija neće izgraditi 1,5 miliona stanova - i to je vest za stolariju",
    "desc": "Dve godine posle obećanja, sagrađeno je 392.400 stanova. Za preostale tri godine trebalo bi 369.200 godišnje. Glavna prepreka nije planiranje ni novac, nego nedostatak obučenih radnika.",
    "body": "Dve godine posle dolaska na vlast, britanska vlada je od obećanih 1,5 miliona novih stanova u pet godina izgradila 392.400 - zaključno sa junom 2026. Za preostale tri godine to znači 369.200 stanova godišnje.\n\nDGB podseća da Britanija taj tempo nije dostigla šezdeset godina. Vlada je već počela da menja jezik kojim govori o cilju.\n\nRazlozi su nabrojani otvoreno: trošak izgradnje kuće skočio je zbog cene materijala i novih propisa, tržište nekretnina je zaglavljeno rastom cena, a planski sistem traži doradu. Ali glavna kočnica, piše autor, oduvek je bila jedna - nedostatak obučenih radnika.\n\nZa stolariju to nije apstraktno. Kada tržište nekretnina ima ponudu, ljudi se sele. A kada se sele, ulažu u renoviranje i zamenu stolarije. Blokirano tržište znači i manje tog novca.\n\n- Šta ovo znači za Balkan? -\nIsti nedostatak radne snage postoji i ovde, samo ga niko nije izmerio. Razlika je što britanski proizvođač ima podatak koji može da pokaže banci i kupcu, a mi imamo osećaj.\n\nAli poenta je praktičnija od statistike. Ako je nedostatak montera stvarna granica rasta, onda ulaganje u mašinu koja skraćuje ciklus vredi više od ulaganja u prodaju koja donosi porudžbine koje nemaš kim da montiraš.\n\nPrebroj koliko si otvora prošlog meseca odbio ili odložio zato što nije bilo ekipe, a ne zato što nije bilo posla. Ako je taj broj veći od nule, tvoje usko grlo nije tržište.",
    "read": "4 min",
    "source": "Double Glazing Blogger",
    "url": "https://www.doubleglazingblogger.com/2026/08/1-5m-new-homes-were-never-going-to-be-built/",
    "img": "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-30T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-007",
    "cat": "trziste",
    "catLabel": "TRŽIŠTE",
    "date": "28. avg 2026",
    "title": "SAD: visoke kamate i inflacija guše prodaju novih kuća",
    "desc": "Povišeni troškovi zaduživanja, rastuća inflacija i opšta ekonomska neizvesnost nastavljaju da koče tražnju kupaca i drže prodaju novih kuća ispod očekivanja.",
    "body": "Window + Door, glasilo američkog udruženja proizvođača stolarije, izveštava da povišeni troškovi zaduživanja, rastuća inflacija i šira ekonomska neizvesnost i dalje koče tražnju kupaca i drže prodaju novih kuća pod pritiskom.\n\nZa proizvođače stolarije to znači jedno: kanal novogradnje se sužava, a kanal zamene postaje relativno važniji.\n\n- Šta ovo znači za Balkan? -\nSrbija, BiH i Severna Makedonija su još uvek u fazi rasta novogradnje, pa se ovo ne tiče nas neposredno. Ali mehanizam je isti svuda: kada cena kredita poraste, prvo stane novogradnja, a tek posle nekoliko kvartala i zamena.\n\nPraktičan zaključak je isti kao i uvek kada se kanal novogradnje suzi - firma koja živi od dva-tri velika investitora najranjivija je, jer gubi 100% prihoda kad ti investitori stanu. Firma koja ima izgrađen kanal prema krajnjem kupcu preživi, jer zamena stolarije ne prestaje - samo se odloži.\n\nAko ti više od polovine prihoda dolazi od manje od pet kupaca, to je danas najveći rizik u tvom poslu, bez obzira što tržište trenutno raste.",
    "read": "2 min",
    "source": "Window + Door",
    "url": "https://www.windowanddoor.com/news/economic-uncertainty-affordability-challenges-weigh-new-home-sales",
    "img": "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-28T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-008",
    "cat": "proizvodi",
    "catLabel": "OKOV",
    "date": "28. avg 2026",
    "title": "Roto predstavio skriveni šarke za krila do 80 kg",
    "desc": "Roto Window & Door Technology uveo je Roto AL Designo | STS 180° - skrivenu šarku za prozorska krila do 176 funti (oko 80 kg), kao proširenje AL Designo linije.",
    "body": "Roto Window & Door Technology predstavio je Roto AL Designo | STS 180°, skrivenu šarku za prozorska krila težine do 176 funti - oko 80 kilograma. Reč je o proširenju postojeće AL Designo linije za aluminijumsku stolariju.\n\nOtvaranje do 180 stepeni uz potpuno skriven okov znači da se krilo može otvoriti do zida, a da se na prozoru ne vidi nijedan element okova.\n\n- Šta ovo znači za Balkan? -\nDva trenda se ovde spajaju i oba stižu na Balkan: veće staklene površine i zahtev da se okov ne vidi. Arhitekte sve češće traže minimalistički izgled, a veća stakla znače teža krila - što stariji okov ne može da nosi.\n\nProblem je što skriveni okov za teška krila menja i proizvodni proces: traži precizniju obradu, drugačiju pripremu profila i obučenog montažera. Nije to stvar koju uvedeš na jednom nalogu.\n\nPraktično pitanje za tvog dobavljača okova ove nedelje: koja je maksimalna težina krila koju tvoj trenutni sistem podržava sa skrivenim okovom, i šta bi bilo potrebno da pređeš na 80 kg. Ako odgovor bude „to nemamo\", to je informacija koja ti treba pre nego što izgubiš prvi projekat zbog nje, a ne posle.",
    "read": "2 min",
    "source": "Window + Door",
    "url": "https://www.windowanddoor.com/news/roto-launches-new-concealed-hinge-side",
    "img": "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-28T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-009",
    "cat": "standardi",
    "catLabel": "OBRAZOVANJE",
    "date": "28. avg 2026",
    "title": "Nemački savez ravnog stakla pokrenuo besplatan digitalni kurs za pripravnike",
    "desc": "Bundesverband Flachglas nudi digitalni osnovni kurs o staklu u šest lekcija, dostupnih za preuzimanje. Namenjen je pripravnicima koji u septembru počinju rad u staklarskoj industriji.",
    "body": "Nemački Bundesverband Flachglas (BF) pokrenuo je digitalni osnovni kurs o staklu za pripravnike koji u septembru počinju rad u industriji. Kurs ima šest lekcija koje su dostupne za preuzimanje.\n\nSadržaj pokriva osnovno znanje o staklu kao materijalu - ono što se u praksi obično uči usput, nesistematično i s greškama koje kasnije koštaju.\n\n- Šta ovo znači za Balkan? -\nOvo je najjeftinija stvar u celoj listi vesti, i verovatno najkorisnija.\n\nNa Balkanu ne postoji zvanična kvalifikacija ni za montera stolarije ni za obradu stakla. Novi radnik uči od kolege, kolega je učio od svog kolege, i svaka greška se prenosi dalje. Posledica je merljiva: reklamacije, škart stakla, pogrešno snimljene mere.\n\nNe treba ti savez da bi ovo rešio. Treba ti šest kratkih dokumenata koje napiše tvoj najbolji majstor, i pravilo da svaki novi radnik prođe kroz njih u prvoj nedelji. To je jedan dan posla i najbolji povrat na uloženo vreme koji postoji u proizvodnji stolarije.\n\nAko ti se to čini kao previše - izračunaj koliko te je koštala poslednja reklamacija zbog pogrešno postavljenog stakla.",
    "read": "2 min",
    "source": "GLASWELT",
    "url": "https://www.glaswelt.de/glas/bundesverband-flachglas-bietet-digitalen-grundkurs-fuer-auszubildende",
    "img": "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-28T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-002",
    "cat": "proizvodi",
    "catLabel": "NOVI PROIZVOD",
    "date": "27. avg 2026",
    "title": "CRL predstavio foliju za privremeno obezbeđenje polomljenog stakla",
    "desc": "Samolepljiva folija se lepi direktno na oštećeno staklo, drži krhotine na okupu i štiti od vremenskih uslova do popravke. Debljina 175 mikrometara, propusnost svetlosti oko 85 odsto.",
    "body": "C.R. Laurence (CRL) uveo je u ponudu foliju za privremeno obezbeđenje oštećenog stakla. Samolepljiva folija se nanosi direktno na napuklo staklo, drži krhotine na okupu, stvara privremenu sigurnosnu barijeru i štiti od vremenskih uticaja i prljavštine dok se ne izvede prava popravka.\n\nDosad se za takvu situaciju najčešće koristila daska - koju treba nabaviti, doneti i montirati. Folija je brža i, kako navode, urednija.\n\nNathalie Peters, direktorka prodaje u CRL-u, ističe propusnost svetlosti od oko 85 odsto pri debljini folije od 175 mikrometara. Izlog ostaje providan dok se čeka zamena stakla.\n\n- Šta ovo znači za Balkan? -\nOvo je mala stavka sa nesrazmerno velikim efektom na odnos sa kupcem. Kada pukne staklo na izlogu ili na stanu, kupac je u panici, a ti nemaš zamensko staklo na lageru - najčešće se čeka nedelju do dve.\n\nTo je tačka u kojoj se najčešće gubi klijent, jer kupac tvoju nemoć doživljava kao nezainteresovanost.\n\nProveri sa svojim dobavljačem stakla ili okova da li ima ovakvu foliju u ponudi i koliko košta rolna. Ako je odgovor da, imaš uslugu koju konkurencija nema: izlazak na teren u roku od 24 sata, privremeno rešenje, i naplaćen izlazak. Ako je odgovor ne, i dalje si saznao šta da pitaš na sledećem sajmu.",
    "read": "2 min",
    "source": "GLASWELT",
    "url": "https://www.glaswelt.de/glas/c-r-laurence-europe-crl-glasbruch-diese-folie-hilft-bei-notverglasungen",
    "img": "https://images.unsplash.com/photo-1590959651373-a3db0f38a961?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-27T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-014",
    "cat": "tehnika",
    "catLabel": "TEHNIKA",
    "date": "26. avg 2026",
    "title": "Povratak \"heritage\" aluminijuma: kupci traže karakter, ne samo U-vrednost",
    "desc": "DGB beleži rast tražnje za aluminijumskim sistemima koji imitiraju tradicionalne čelične prozore - tanke prečke, tamne boje, podeljena polja. Trend dolazi iz enterijera i vraća se na fasadu.",
    "body": "Double Glazing Blogger beleži jasan pomak u tražnji: kupci se vraćaju karakteru. Panelisani zidovi, kuhinje u modernom seoskom stilu, tradicionalni okov i nasleđene palete boja ponovo su u modi - i taj trend je stigao do stolarije.\n\nU praksi to znači aluminijumske sisteme koji imitiraju stare čelične prozore: uske prečke, podeljena polja, mat crne i antracit nijanse, vidljivi okov s karakterom. Aluminijum je jedini materijal koji može da isporuči tu vizuelnu tananost, a da zadrži termiku koju traži savremena regulativa.\n\n- Šta ovo znači za Balkan? -\nOvo je prilika za maržu, ne za volumen. Balkansko tržište je i dalje pretežno cenovno, ali segment renoviranja starih gradskih stanova i kuća u centrima - Beograd, Zagreb, Sarajevo, Ljubljana - traži upravo takav izgled i spreman je da plati više. Proizvođač koji u ponudi ima heritage liniju izlazi iz direktnog cenovnog poređenja s konkurencijom koja nudi standardni beli petokomorni profil.\n\nPraktično: pitaj svog dobavljača aluminijumskih sistema šta ima u toj kategoriji, i napravi dve reference. Fotografija ugrađenog heritage prozora u starom stanu prodaje bolje od bilo kog kataloga.",
    "read": "3 min",
    "source": "Double Glazing Blogger",
    "url": "https://www.doubleglazingblogger.com/2026/08/the-rise-of-heritage-aluminium/",
    "img": "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-26T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-003",
    "cat": "kompanije",
    "catLabel": "INDUSTRIJA",
    "date": "25. avg 2026",
    "title": "AGC Interpane isporučio fasadno staklo za milanski neboder Thetris",
    "desc": "Poslovna zgrada viša od 100 metara u Milanu dobija posebno razvijen omotač koji spaja arhitektonski dizajn sa energetskom efikasnošću i prilagođavanjem klimi. Fasadna stakla isporučio je AGC Interpane.",
    "body": "Poslovna zgrada „Thetris\" u Milanu, viša od 100 metara, dobija posebno razvijen omotač zgrade. Prema navodima GLASWELT-a, rešenje spaja arhitektonski dizajn sa visokom energetskom efikasnošću i prilagođavanjem klimatskim uslovima. Fasadna stakla za sunčevu zaštitu isporučio je AGC Interpane.\n\n- Šta ovo znači za Balkan? -\nProjekti ovog obima ne stižu na Balkan u istom obliku, ali specifikacija stiže. Ono što se danas ugrađuje na milanski neboder, za dve do tri godine traži arhitekta na poslovnoj zgradi u Beogradu ili Zagrebu - jer to vidi u istim časopisima.\n\nZa fasadere i proizvođače koji rade na većim objektima to znači jedno: staklo sa sunčevom zaštitom prestaje da bude dodatak i postaje deo osnovne specifikacije.\n\nPitaj svog dobavljača stakla koje sunčevozaštitne pakete drži na lageru za region i kakvi su rokovi. Ako je rok duži od šest nedelja, to je podatak koji moraš imati pre nego što daš ponudu, a ne posle.",
    "read": "2 min",
    "source": "GLASWELT",
    "url": "https://www.glaswelt.de/glas/agc-interpane-mailaender-hochhaus-thetris-mit-massgeschneiderten-sonnenschutzglaesern",
    "img": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-25T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-005",
    "cat": "trziste",
    "catLabel": "TRŽIŠTE",
    "date": "25. avg 2026",
    "title": "Eko-Okna snizile cene aluminijumskih škura na tri meseca - i to nije akcija, nego ulazak u kategoriju",
    "desc": "Najveći poljski proizvođač stolarije snizio je cene aluminijumskih škura Eko Persiane na naredna tri meseca. Cilj nije rasprodaja, nego da distributeri ubace proizvod u ponudu i podignu vrednost porudžbine kroz cross-selling.",
    "body": "Eko-Okna, najveći poljski proizvođač stolarije, snizile su cene aluminijumskih škura Eko Persiane na naredna tri meseca. Nove cene automatski su primenjene na njihovoj prodajnoj platformi eko4u i važe za sve partnere.\n\nRazlog nije prazan magacin. Product Manager za aluminijum Michał Obrusnik otvoreno kaže da je cilj podići svest o postojanju proizvoda i podstaći distributere da ga uvedu u ponudu - a da je glavni prodajni argument zapravo dizajn, ne cena.\n\nLogika je jednostavna: škure u mediteranskom stilu rastu u tražnji i za distributera su isplativija alternativa roletnama i žaluzinama. Aluminijum umesto drveta znači gotovo bez održavanja i manje reklamacija. Montaža je jednostavna - direktno na zid ili na ram - i ne traži novo znanje kod montažera.\n\n- Šta ovo znači za Balkan? -\nOvde su dve odvojene poruke i obe su važne.\n\nPrva: ovako izgleda kada proizvođač koristi cenu kao alat za ulazak u kategoriju, a ne kao popust iz očaja. Snižena cena traje tačno tri meseca, vezana je za jedan proizvod i ima jasan cilj - da distributer napravi prvu prodaju. Posle toga cena se vraća, a proizvod ostaje u katalogu.\n\nDruga, praktičnija: cross-selling na postojeću porudžbinu je najjeftiniji rast koji balkanski proizvođač može da ostvari. Kupac koji već naručuje prozore za kuću na jugu Srbije, u Hercegovini ili na primorju je najlakši mogući kupac za škure, komarnike ili staklenu ogradu. Ne treba ti nova akvizicija - treba ti da to bude u ponudi i da prodavac zna da pita. Proveri koliko tvojih porudžbina sadrži više od jedne kategorije proizvoda. Ako je manje od trećine, tu ti stoji novac.",
    "read": "3 min",
    "source": "OknoNet",
    "url": "https://oknonet.pl/eko-okna-obnizaja-ceny-eko-persiane-wiecej-mozliwosci-dla-dystrybutorow/",
    "img": "https://images.unsplash.com/photo-1523413363574-c30aa1c2a516?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-25T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-006",
    "cat": "trziste",
    "catLabel": "TRŽIŠTE",
    "date": "21. avg 2026",
    "title": "Nemački VFF objavljuje prognozu tržišta prozora za 2027, odvojeno za sanaciju i novogradnju",
    "desc": "Savez Fenster + Fassade održava 29. septembra konferenciju \"Statistika i tržište\" sa ažuriranim brojevima za prozore i spoljna vrata, podeljenim na sanaciju i novogradnju te stambenu i nestambenu gradnju, plus prognozu za 2027.",
    "body": "Nemački Verband Fenster + Fassade (VFF) organizuje 29. septembra 2026. konferenciju „Statistika i tržište\" u Frankfurtu, uz mogućnost onlajn učešća.\n\nU fokusu su ažurirani tržišni brojevi za prozore i spoljna vrata, razdvojeni po dve ose: sanacija naspram novogradnje, i stambena naspram nestambene gradnje. Uz to ide prognoza za 2027. godinu, koju pripremaju B+L Marktdaten i Heinze.\n\nProgram pokriva i razvoj modularne i serijske gradnje, monitoring nemačkih subvencija za energetsku efikasnost (BEG), i građevinski izgled za Evropu u 2026.\n\nFrank Lange, direktor VFF-a, kaže da ovakvi podaci firmama daju „mantinele za planiranje\" i da u nesigurnim vremenima to može biti konkurentska prednost.\n\n- Šta ovo znači za Balkan? -\nNa Balkanu ne postoji nijedan izvor koji razdvaja tržište stolarije na sanaciju i novogradnju. To nije akademsko pitanje - to su dva potpuno različita biznisa. Novogradnja znači jednog kupca, veliku količinu, dugačke rokove plaćanja i pritisak na cenu. Sanacija znači stotine malih kupaca, brzu naplatu, veću maržu po otvoru i potpuno drugačiju prodaju.\n\nNemački podaci su najbolji dostupni proxy dok se regionalni ne pojave, jer tržišta prolaze kroz iste faze s pomakom. Ako u Nemačkoj udeo sanacije nastavi da raste na račun novogradnje, to je najava onoga što stiže ovamo.\n\nPraktično: razdvoj svoje prihode na te dve kategorije za poslednje tri godine i pogledaj koja raste. Ta jedna tabela reći će ti više o tvom sledećem potezu nego bilo koja tuđa prognoza.",
    "read": "3 min",
    "source": "GLASWELT",
    "url": "https://www.glaswelt.de/fenster/vff-fachtagung-marktzahlen-und-prognosen-fuer-fenster-und-fassaden",
    "img": "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-21T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-010",
    "cat": "tehnologija",
    "catLabel": "TEHNOLOGIJA",
    "date": "21. avg 2026",
    "title": "Saint-Gobain potpisao ugovor s Microsoftom za uvođenje AI u građevinske materijale",
    "desc": "Saint-Gobain je 28. jula potpisao okvirni sporazum s Microsoftom o širenju digitalnih tehnologija i veštačke inteligencije kroz sve operacije grupe. Cilj su produktivnost, održivost i razvoj rešenja s nižim ugljeničnim otiskom.",
    "body": "Saint-Gobain, jedan od najvećih svetskih proizvođača građevinskih materijala i stakla, potpisao je okvirni sporazum s Microsoftom o proširenju upotrebe digitalnih tehnologija i veštačke inteligencije kroz poslovanje grupe.\n\nSporazum, objavljen 28. jula, pokriva tri pravca: povećanje produktivnosti u proizvodnji, smanjenje ugljeničnog otiska proizvodnih linija, i razvoj rešenja za data centre - segment koji poslednjih godina postaje ozbiljan kupac fasadnih i staklenih sistema.\n\nZa industriju stakla ovo nije marketinška vest. Saint-Gobain je vlasnik velikog dela evropskih kapaciteta float stakla, a svaka optimizacija peći i linija za obradu direktno se prenosi na cenu i raspoloživost stakla nizvodno.\n\n- Šta ovo znači za Balkan? -\nBalkanski proizvođači stolarije kupuju staklo od distributera koji ga uzimaju upravo od ovakvih grupacija. Ako AI optimizacija smanji škart i produži vek peći, to se dugoročno vidi kao stabilnija cena IGU jedinica. Kratkoročno ne menja ništa - ali je signal u kom pravcu ide struktura troškova kod dobavljača. Vredi to imati u vidu pri pregovoru o višegodišnjim ugovorima s distributerima stakla.",
    "read": "3 min",
    "source": "Double Glazing Blogger",
    "url": "https://www.doubleglazingblogger.com/2026/08/saint-gobain-signs-microsoft-agreement-to-accelerate-ai-use-in-construction/",
    "img": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-21T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-011",
    "cat": "proizvodnja",
    "catLabel": "PROIZVODNJA",
    "date": "21. avg 2026",
    "title": "Morley Glass prešao 3.000 tona recikliranog stakla iz iskorišćenih IGU jedinica",
    "desc": "Britanski proizvođač integralnih žaluzina objavio je da je kroz svoj program prikupljanja starih IGU jedinica od montažera proizveo preko 3.000 tona kaleta. Program radi od 2021.",
    "body": "Morley Glass, najveći britanski proizvođač integralnih žaluzina po meri, objavio je da je kroz svoj program reciklaže prešao 3.000 tona kaleta - drobljenog stakla dobijenog iz starih IGU jedinica koje prikuplja od svojih kupaca montažera.\n\nProgram je pokrenut 2021. godine i bio je prvi u Britaniji koji je reciklažu iskorišćenih staklopaketa organizovao u ozbiljnom obimu. Montažeri vraćaju demontirane jedinice, a Morley ih šalje na drobljenje i vraćanje u proizvodni lanac.\n\nEkonomija je jednostavna: staro staklo inače završava na deponiji uz trošak odlaganja. Kada se organizuje povratni tok, trošak odlaganja se pretvara u sirovinu koja ima cenu.\n\n- Šta ovo znači za Balkan? -\nNa Balkanu se demontirana stolarija i staro staklo najčešće tretiraju kao otpad koji montažer plaća da odnese. Nijedan regionalni proizvođač nema organizovan povratni tok. To je istovremeno trošak koji svi imaju i prilika koju niko ne koristi. Prvi proizvođač koji montažerima ponudi besplatno preuzimanje demontiranih jedinica dobija dve stvari: argument u prodaji prema investitorima koji traže dokaz o održivosti, i sirovinu koja ima tržišnu vrednost. Za firme koje rade na javnim nabavkama, gde ekološki kriterijumi ulaze u bodovanje, ovo prestaje da bude tema za kasnije.",
    "read": "2 min",
    "source": "Double Glazing Blogger",
    "url": "https://www.doubleglazingblogger.com/2026/08/morley-glass-smashes-through-3000-tonne-mark-for-recycled-glass/",
    "img": "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-21T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-015",
    "cat": "kompanije",
    "catLabel": "INDUSTRIJA",
    "date": "21. avg 2026",
    "title": "Peti američki proizvođač prozora i vrata za manje od godinu dana otišao u stečaj",
    "desc": "Gulfside Windows, Doors & More iz Tampe podneo je zahtev za Chapter 11 19. avgusta - obaveze od 1,5 miliona dolara naspram imovine od svega 323.000. Firma je peta američka kompanija za prozore i vrata koja u poslednjih osam meseci traži zaštitu od poverilaca, u talasu koji prati rast cena aluminijuma i uvoznih carina.",
    "body": "Gulfside Windows, Doors & More, kompanija iz Tampe na Floridi specijalizovana za udarno otporne (impact) prozore i vrata, podnela je 19. avgusta zahtev za zaštitu od poverilaca po Chapter 11 pred američkim stečajnim sudom za srednji okrug Floride. Prema sudskim dokumentima, obaveze firme iznose oko 1,5 miliona dolara, dok je njena imovina procenjena na svega 322.898 dolara - manje od četvrtine duga.\n\nFirma je osnovana 2015. i do sada je realizovala preko 4.800 projekata, radeći sa brendovima kao što su PGT, Simonton, Therma-Tru i Eastern Architectural Systems, sa fokusom na prozore i vrata otporne na uragane za tri okruga oko Tampe. Izvršni direktor Aaron Shoham potpisao je zahtev, a firmu zastupa advokat Shawn M. Yesner.\n\nGulfside nije usamljen slučaj. Prema pregledu portala WhatNow, ovo je peta američka firma iz sektora prozora i vrata koja je od decembra 2025. do avgusta 2026. tražila zaštitu od poverilaca - pre nje su to učinili Sky-Frame iz Los Anđelesa (decembar 2025), Fabrication Designs iz Merilenda (mart 2026), Armored Impact Windows & Doors iz Boka Ratona (mart 2026) i BNT Services iz Pompano Biča (jul 2026). Izveštaj magazina USGlass iz januara 2026. povezuje pritisak na maržu sa rastom cena metalnih prozora i vrata i uvoznim carinama koje su na snazi tokom cele godine.\n\n- Šta ovo znači za Balkan? -\nBalkanski proizvođači uglavnom ne izvoze direktno na američko tržište u velikom obimu, ali priča je upozorenje šireg tipa: kad se troškovi sirovina i uvozne dažbine menjaju brže nego što firma stigne da prilagodi cenovnik, čak i kompanije sa hiljadama realizovanih projekata mogu da padnu za manje od godinu dana. Isti pritisak - rast cene aluminijuma, energetski troškovi, duži rokovi naplate - postoji i na Balkanu. Razlika je što ovde tržište nije izloženo naglim promenama carinske politike, već sporijem, ali stalnom rastu troškova.",
    "read": "3 min",
    "source": "WhatNow",
    "url": "https://whatnow.com/news/trending/tampa-bay-business-serving-homeowners-with-impact-windows-files-chapter-11-bankruptcy/",
    "img": "https://images.unsplash.com/photo-1601084881623-cdf9a8ea242c?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-21T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-016",
    "cat": "trziste",
    "catLabel": "TRŽIŠTE",
    "date": "20. avg 2026",
    "title": "Aluminijum na LME prešao 2.700 EUR/t - troškovi rastu za sve koji kupuju profil",
    "desc": "Rast od 4,8% u 30 dana gura cene aluminijumskog profila na višemesečni maksimum. Proizvođači koji nisu zaključali cene isporuke do kraja kvartala osetiće pritisak na marže već u septembru.",
    "body": "Cena aluminijuma na London Metal Exchange (LME) probila je 2.700 EUR/t sredinom avgusta 2026 - rast od 4,8% u samo 30 dana i najviši nivo u poslednjih nekoliko meseci. Za industriju aluminijumske stolarije to nije apstraktan broj: aluminijum čini između 40% i 60% ukupnih troškova materijala kod proizvođača AL profila, prozora i fasadnih sistema.\n\nRast cene na LME se u kalkulacije fabrikanata obično prenosi sa zakašnjenjem od 4 do 8 nedelja, u zavisnosti od toga da li imaju ugovorene fiksne cene sa dobavljačima profila ili kupuju po tekućoj (spot) ceni. Proizvođači koji su zaključali cene isporuke do kraja trećeg kvartala 2026. za sada su zaštićeni - ali ugovori koji ističu u septembru i oktobru već uključuju novi, viši nivo.\n\nMatematika je jednostavna: skok cene od 5% na LME, bez zaštitnih mehanizama u ugovoru sa dobavljačem, direktno smanjuje maržu proizvođača za 2-3 procentna poena, jer se retko može odmah prevaliti na krajnjeg kupca kroz već ugovorene poslove.\n\n- Šta ovo znači za Balkan? -\nProizvođači AL stolarije u regionu koji rade sa dobavljačima profila po spot ceni (bez fiksiranih ugovora) treba da prate LME svakodnevno i da razmotre hedžing ili barem kratkoročno fiksiranje cena za narudžbe koje isporučuju u narednih 60-90 dana. Ko posluje sa fiksnim cenama do kraja godine ima prostor da iskoristi trenutnu situaciju i ponudi konkurentnije cene dok se tržište ne izravna.",
    "read": "2 min",
    "source": "LME / analiza redakcije",
    "url": "https://www.lme.com/en/metals/ev/lme-aluminium",
    "img": "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-20T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-004",
    "cat": "investicije",
    "catLabel": "INVESTICIJA",
    "date": "19. avg 2026",
    "title": "Şişecam pojačava prisustvo u Evropi: 3,54 milijarde evra u prvoj polovini 2026.",
    "desc": "Turski staklarski gigant objavio je neto prihod od oko 3,54 milijarde evra u H1 2026, sa 61% prihoda iz inostranstva. Pustio je u rad nove linije za oplemenjivanje stakla u Turskoj i Evropi i otvorio prvu fabriku staklene ambalaže u Mađarskoj.",
    "body": "Şişecam je u prvoj polovini 2026. ostvario neto prihod od oko 3,54 milijarde evra (oko 122 milijarde turskih lira), uz investicije od oko 348 miliona evra i izvoz preko 400 miliona evra. Udeo međunarodnog poslovanja u ukupnom prihodu iznosio je 61 odsto.\n\nU istom periodu grupa je pustila u rad nove linije za oplemenjivanje stakla u Turskoj i u Evropi, a u Mađarskoj je realizovala prvu investiciju u pogon za staklenu ambalažu na evropskom tlu.\n\nCEO Can Yücel opisao je period kao vođen neizvesnošću i volatilnim troškovima energije i logistike, uz fokus na efikasnost, disciplinu troškova i upravljanje likvidnošću. Grupa je u prvom kvartalu uspešno emitovala evroobveznicu uz jaku tražnju investitora.\n\n- Šta ovo znači za Balkan? -\nŞişecam je geografski najbliži veliki proizvođač stakla balkanskim proizvođačima - bliži od zapadnoevropskih grupacija. Nove linije za oplemenjivanje u Turskoj i Evropi znače da low-E i solarno staklo više ne moraju da putuju iz Nemačke ili Belgije, a kraći transportni krak je direktno kraći rok isporuke i manji trošak.\n\nPraktično: ako trenutno kupujete oplemenjeno staklo isključivo preko zapadnih distributera, vredi tražiti ponudu i preko turskog i mađarskog kanala i uporediti ukupan trošak s transportom i rokom. Razlika u roku isporuke od dve nedelje na velikom projektu vredi više od nekoliko procenata razlike u ceni.",
    "read": "3 min",
    "source": "GLASWELT",
    "url": "https://www.glaswelt.de/glas/starkes-wachstum-sisecam-verstaerkt-engagement-europa",
    "img": "https://images.unsplash.com/photo-1518005020951-eccb494ad742?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-19T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-017",
    "cat": "standardi",
    "catLabel": "REGULATIVA",
    "date": "19. avg 2026",
    "title": "EU EPBD: od januara 2027. novi objekti moraju imati U ≤ 1,0 za prozore",
    "desc": "Revidovana Energy Performance of Buildings Directive konačno dobija jasne tehničke zahteve za stolariju. Države članice moraju je implementirati do decembra 2026. Za balkanske izvoznike koji rade EU projekte - nije opcija nego uslov.",
    "body": "Revidovana Energy Performance of Buildings Directive (EPBD) je na snazi od 2024, ali do sada su tehnički detalji za stolariju bili nejasni - svaka država članica je nagoveštavala svoje pragove. Sada je jasno: od 1. januara 2027, svi novi objekti u EU moraju ispuniti minimalne zahteve energetske efikasnosti koji u praksi znače U-vrednost prozora od najviše 1,0 W/m²K u većini klimatskih zona.\n\nDržave članice imaju rok do decembra 2026. da direktivu prenesu u nacionalno zakonodavstvo - što znači da će konkretni pravilnici (i eventualne nacionalne razlike u pragovima po klimatskoj zoni) izlaziti tokom cele jeseni 2026.\n\nZa proizvođače to nije apstraktna regulativa. U ≤ 1,0 praktično isključuje jednostruko staklo i osnovne dvostruke IGU pakete bez naprednog low-E premaza ili toplo-prekinutog rama - trostruko staklo i kvalitetan termički prekid postaju standard, ne opcija, za sve koji rade EU projekte.\n\n- Šta ovo znači za Balkan? -\nBalkanske zemlje van EU (Srbija, BiH, Severna Makedonija) nisu direktno obavezane EPBD-om. Ali svaki proizvođač koji izvozi u Hrvatsku, Sloveniju, Rumuniju ili dalje na zapad mora da uskladi katalog sa novim pragom. Ko još uvek nudi samo U=1,3–1,4 sisteme kao \"premium\" liniju, ima manje od godinu dana da to promeni pre nego što izgubi pristup EU tenderima i privatnim projektima.",
    "read": "3 min",
    "source": "Evropska komisija - EPBD",
    "url": "https://energy.ec.europa.eu/topics/energy-efficiency/energy-efficient-buildings/energy-performance-buildings-directive_en",
    "img": "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-19T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-012",
    "cat": "standardi",
    "catLabel": "STANDARDI",
    "date": "18. avg 2026",
    "title": "Britanija uvela prve zvanične kvalifikacije za montažu i snimanje stolarije",
    "desc": "NOCN Group je početkom avgusta pokrenuo NVQ Level 2 diplomu za montažu stolarije i NVQ Level 3 sertifikat za snimanje mera. Prve su u nizu zvaničnih kvalifikacija za industriju prozora i stakla.",
    "body": "Inicijativa Building Our Skills objavila je da je NOCN Group početkom avgusta pokrenuo dve nove zvanične kvalifikacije za industriju stolarije, stakla i staklarstva: NVQ Level 2 diplomu za montažu stolarije i NVQ Level 3 sertifikat za snimanje mera.\n\nOve dve su prve u planiranom nizu kvalifikacija koje treba da pokriju ceo lanac - od montaže do tehničkog snimanja objekta pre proizvodnje.\n\nRazlog je poznat svima u struci: montaža je mesto gde se najviše gubi. Loše snimljena mera i loše izvedena ugradnja poništavaju kvalitet profila, okova i stakla, bez obzira koliko je proizvod dobar. U Britaniji je nedostatak sertifikovanih montažera godinama identifikovan kao usko grlo industrije.\n\n- Šta ovo znači za Balkan? -\nIsti problem, bez istog odgovora. Na Balkanu ne postoji priznata kvalifikacija za montera stolarije - uči se na gradilištu, od kolege, bez standarda. Posledica je da proizvođač koji ulaže u kvalitet profila i okova ne može da kontroliše poslednjih 10% procesa, gde nastaje 80% reklamacija. Dok se ne pojavi zvanična kvalifikacija, jedini praktičan potez je interna obuka: sopstveni kontrolni list za snimanje mera i za montažu, i evidencija ko je šta ugradio. To je najjeftinija mera za smanjenje reklamacija koju svaki proizvođač može da uvede ove nedelje.",
    "read": "3 min",
    "source": "Double Glazing Blogger",
    "url": "https://www.doubleglazingblogger.com/2026/08/building-our-skills-announces-launch-of-new-installation-and-surveying-qualifications/",
    "img": "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-18T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-020",
    "cat": "trziste",
    "catLabel": "ANALIZA",
    "date": "14. avg 2026",
    "title": "Renovacija sve više nadmašuje novu gradnju u EU",
    "desc": "Eurostat podaci za H1 2026 potvrđuju trend koji redakcija prati od početka godine: u više zemalja EU, uključujući Sloveniju i Hrvatsku, više novca ide u energetsku obnovu nego u nove objekte. Za proizvođače stolarije to znači kraće serije, više varijanti, brže isporuke.",
    "body": "Ovo je analitički tekst redakcije, ne prenos jedne konkretne vesti - zasnovan na javno dostupnim Eurostat serijama o građevinskoj aktivnosti (indeks obima građevinskih radova, po tipu: nova gradnja vs. renovacija) za period H1 2026.\n\nOpšti obrazac koji se vidi u više zapadnoevropskih i pojedinim zemljama regiona (uključujući Sloveniju i delimično Hrvatsku): dozvole za novu stambenu gradnju stagniraju ili blago padaju, dok obim ugovorenih radova na energetskoj obnovi postojećih zgrada raste - gurnut kombinacijom EU fondova za renovaciju (Renovation Wave inicijativa), viših cena energenata i EPBD zahteva koji se primenjuju i na postojeći fond zgrada pri većim rekonstrukcijama.\n\nZa proizvođače stolarije praktična posledica: umesto jedne velike narudžbe od 200 identičnih prozora za novogradnju, sve češće dolaze narudžbe od 15-30 prozora različitih dimenzija za renovaciju stambene zgrade - veći administrativni trošak po jedinici, ali i veća marža ako je proces kalkulacije i proizvodnje prilagođen.\n\n- Šta ovo znači za Balkan? -\nSlovenija i Hrvatska (kao EU članice) prve osećaju ovaj pomak jer imaju pristup EU fondovima za renovaciju. Srbija, BiH i Severna Makedonija kasne nekoliko godina, ali isti obrazac se već nazire kod većih gradova (Beograd, Novi Sad) gde stare zgrade prelaze na energetsku sanaciju kroz lokalne subvencije. Proizvođači koji već sada prilagode proizvodnju kratkim, varijabilnim serijama biće spremni kad talas stigne i ovamo.",
    "read": "3 min",
    "source": "Eurostat / analiza redakcije",
    "url": "https://ec.europa.eu/eurostat",
    "img": "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-14T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-021",
    "cat": "proizvodi",
    "catLabel": "NOVI PROIZVOD",
    "date": "13. avg 2026",
    "title": "Reynaers Aluminium: CS 104 sistem za hladnu klimu dolazi u Srbiju i Rumuniju",
    "desc": "Belgijski Reynaers širi distribuciju svog visokoizolacionog CS 104 vratnog sistema (pogodan za pasivnu gradnju) na srpsko i rumunsko tržište kroz lokalne kancelarije. Reynaers je u Rumuniji prisutan od 1996, a u Srbiji ima sopstveno predstavništvo.",
    "body": "Reynaers Aluminium, belgijski proizvođač arhitektonskih aluminijumskih sistema, pojačava distribuciju svog CS 104 (Concept System 104) vratnog sistema kroz lokalne kancelarije u Rumuniji i Srbiji.\n\nCS 104 je pozicioniran kao rešenje za pasivnu i niskoenergetsku gradnju - visok nivo termičke izolacije kombinovan sa vrhunskom vodo- i vazdušnom nepropusnošću, što ga svrstava u segment premium ulaznih i baltičkih vrata za zahtevne klimatske uslove. Sistem se već koristi u zapadnoevropskim projektima gde je EPBD standard odavno primenjen.\n\nReynaers je u Rumuniji prisutan od 1996. sa preko 500 realizovanih projekata, dok u Srbiji posluje kroz sopstveno predstavništvo (Reynaers Aluminium d.o.o.) koje pokriva prodaju, tehničku podršku i obuku fabrikanata.\n\n- Šta ovo znači za Balkan? -\nSa EU EPBD standardom koji od 2027. traži U ≤ 1,0 za nove objekte, sistemi poput CS 104 prestaju da budu nišni \"premium\" izbor i postaju osnovni zahtev za projekte koji ciljaju EU tržište ili investitore koji finansiraju kroz EU fondove. Fabrikanti u regionu koji rade sa Reynaers profilima imaju priliku da se pozicioniraju rano na ovom segmentu pre nego što potražnja eksplodira.",
    "read": "2 min",
    "source": "Reynaers Group",
    "url": "https://www.reynaers.com/products/doors/cs-104",
    "img": "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-13T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-013",
    "cat": "trziste",
    "catLabel": "TRŽIŠTE",
    "date": "10. avg 2026",
    "title": "Britanija se sprema da zabrani lažne popuste u prodaji stolarije",
    "desc": "Praksa da se početna ponuda postavi na 20.000 funti pa \"posle poziva šefu\" spusti na 6.000 mogla bi da postane protivzakonita. Industrija decenijama pokušava da se otarasi te reputacije.",
    "body": "Britanska industrija stolarije decenijama nosi stereotip agresivnog prodavca koji sedi tri sata u dnevnoj sobi, počne od ponude od 20.000 funti, pa je posle \"poziva šefu\" spusti na 6.000.\n\nDGB piše da bi ta praksa uskoro mogla da postane protivzakonita. Regulatorni pritisak ide ka tome da se veštački naduvana početna cena, koja postoji samo da bi popust izgledao veliki, tretira kao obmanjujuća poslovna praksa.\n\nPošteni lokalni montažeri godinama su bili u nepovoljnijem položaju: oni daju realnu cenu odmah, i onda gube posao od konkurencije koja \"daje 70% popusta\".\n\n- Šta ovo znači za Balkan? -\nOva praksa postoji i ovde, samo u manjim iznosima i bez regulatornog pritiska. Efekat je isti: kupac gubi sposobnost da uporedi ponude, jer ne zna šta je cena, a šta pozorište. Za proizvođača koji radi s poštenom kalkulacijom to je direktan gubitak posla.\n\nPraktičan potez ne zahteva zakon. Ako u ponudi jasno razdvojiš stavke - profil, staklo, okov, montaža, PDV - i objasniš zašto je cena takva, kupac dobija način da uporedi tebe s konkurencijom koja daje jedan zbirni broj s \"popustom\". Transparentna ponuda je prodajni alat, ne samo etičko pitanje. Konfiguratori i softver za ponude to rade automatski i tu leži deo njihove vrednosti.",
    "read": "4 min",
    "source": "Double Glazing Blogger",
    "url": "https://www.doubleglazingblogger.com/2026/08/fake-discount-structures-may-be-about-to-end/",
    "img": "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-10T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-026",
    "cat": "kompanije",
    "catLabel": "INDUSTRIJA",
    "date": "7. avg 2026",
    "title": "Owens Corning zatvara fabriku vrata u Indijani, otpušta 130 radnika",
    "desc": "Pogon u Walkertonu (Indijana), nasleđen kupovinom Masonite-a 2024, zatvara se do kraja oktobra 2026 - peti zatvoreni pogon vrata za godinu i po. Prihodi doors segmenta u Q1 2026. pali su 12% na 475 miliona dolara.",
    "body": "Owens Corning zatvara pogon za unutrašnja vrata u Walkertonu, Indijana, do kraja oktobra 2026. Oko 130 radnih mesta ide u dva talasa - otkazi 19. septembra i 2. oktobra, uz poslednja razdvajanja do 29. oktobra dok se pogon zvanično ne zatvori.\n\nOvo je peti pogon koji se zatvara otkako je Owens Corning u maju 2024. kupio Masonite. Isti pogon u Walkertonu je, dok je još bio u vlasništvu Masonite-a, 2022. već smanjio broj zaposlenih za trećinu (220 radnih mesta).\n\nBrojevi iza odluke: u Q1 2026. prihodi doors segmenta pali su 12% na 475 miliona dolara. EBITDA prepolovljena - sa 68 na 34 miliona dolara. U aprilu je Owens Corning prodao i tri distribucijska centra vrata kompaniji Metrie.\n\n- Šta ovo znači za Balkan? -\nGlobalna industrija vrata se konsoliduje. Za balkanske distributere to može značiti promene u dobavljačkom lancu i dostupnosti određenih modela. Ali i otvaranje: regionalni igrači koji mogu garantovati brzu isporuku i servis dobijaju prednost koju korporativni giganti teško nude sa 10.000 km udaljenosti.",
    "read": "3 min",
    "source": "DWM Magazine",
    "url": "https://www.dwmmag.com/2026/08/07/owens-corning-shutters-walkerton-door-plant-eliminating-130-jobs/",
    "img": "https://images.unsplash.com/photo-1601084881623-cdf9a8ea242c?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-07T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-024",
    "cat": "standardi",
    "catLabel": "STANDARDI",
    "date": "4. avg 2026",
    "title": "Novi američki standard za montažu prozora - prvi put od 2012.",
    "desc": "FGIA i WDMA objavili su AAMA/WDMA 100-26, ažurirani standard za ugradnju prozora sa montažnim flanšama u membranske drenažne sisteme. Prethodna verzija bila je iz 2012 - 14 godina bez revizije.",
    "body": "FGIA (Fenestration and Glazing Industry Alliance) i WDMA (Window & Door Manufacturers Association) zajedno su objavili AAMA/WDMA 100-26 - ažurirani standard za ugradnju prozora sa montažnim flanšama u membranske drenažne sisteme u novogradnji. Prethodna verzija bila je iz 2012 - 14 godina bez revizije.\n\nStandard pokriva specifičan, ali važan slučaj: ugradnju u membranske drenažne sisteme koji su dominantni u severnoameričkoj gradnji i sve prisutniji u zapadnoj Evropi. Dokument je odmah dostupan u onlajn prodavnicama obe asocijacije.\n\nOvo je, kažu, prvi u nizu zajedničkih standarda koje dve organizacije planiraju da objavljuju. Signal: industrija se konsoliduje i oko normativnog okvira, ne samo oko tržišta.\n\n- Šta ovo znači za Balkan? -\nNa Balkanu važe EN standardi - EN 14351, RAL smernice za montažu, lokalni normativi. AAMA direktno ne obavezuje. Ali izvoznici koji rade za Austriju, Nemačku ili Skandinaviju znaju da ti kupci prate globalne trendove. Ažuriranje američkih normi najavljuje smer: stroža dokumentacija montaže, više odgovornosti za izvođača.",
    "read": "2 min",
    "source": "Window + Door",
    "url": "https://www.windowanddoor.com/news/updated-industry-standard-published-installation-windows-mounting-flanges",
    "img": "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-04T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-030",
    "cat": "proizvodi",
    "catLabel": "OKOV",
    "date": "4. avg 2026",
    "title": "VBH greenteQ: detalj koji kupci primete, a mnogi proizvođači zaborave",
    "desc": "Poštanski otvor na ulaznim vratima - sitnica koja kupca ili ubedi ili ne. VBH nudi paletu letterplate otvora, od inoks za more do Omega Slim za tankookvirena kompozitna vrata.",
    "body": "Poštanski otvor na ulaznim vratima - na njega se ne misli dok nije problem. Previše nizak, kriva boja, ne brtvi dobro ili izgleda jeftino uz skup okov. Kupac to primeti. Proizvođač obično ne.\n\nVBH distribucija nudi paletu letterplate otvora za proizvođače vrata iz greenteQ palete, uključujući inoks izvedbu za priobalne lokacije gde sve korodira brže nego što bi trebalo.\n\nZvezda kataloga: Omega Slim. Projektovan za slim mid-rail i kompozitna vrata sa tankim okvirima. Dimenzije: 56 mm visina, teleskopska regulacija za debljine od 40 do 70 mm, otvaranje krilaca do 180° sa obe strane. Devet boja unutar greenteQ Suite palete. Garancija: 20 godina na površinu.\n\n- Šta ovo znači za Balkan? -\nVBH distribuira u više balkanskih zemalja. Za proizvođače koji rade slim profil kompozitna vrata - ili koji žele da podignu nivo finalne obrade - Omega Slim je konkretan odgovor na specifičan problem.",
    "read": "2 min",
    "source": "Window News UK",
    "url": "https://www.windownews.co.uk/letterplates-take-your-pick/",
    "img": "",
    "datumISO": "2026-08-04T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-023",
    "cat": "kompanije",
    "catLabel": "AKVIZICIJA",
    "date": "3. avg 2026",
    "title": "ASSA ABLOY kupuje Gunnebo Entrance Control - ulazna kontrola sve je u jednoj ruci",
    "desc": "Još jedna akvizicija giganta koji polako apsorbuje sve što se tiče otvaranja i zatvaranja vrata. Gunnebo radi brzoprolazne kapije i sigurnosne sisteme za aerodrome - oko 670 zaposlenih, prihod ~151 mil. EUR (2025), pogoni na tri kontinenta.",
    "body": "ASSA ABLOY je objavio dogovor o kupovini Gunnebo Entrance Control - kompanije koja pravi brzoprolazne kapije, masovne tranzitne prolaze i sigurnosna rotirajuća vrata za aerodrome (Sofija, Madrid-Barahas) i operatore poput Swedavia. Gunnebo ima oko 670 zaposlenih, sedište u britanskom Maresfildu, pogone u Evropi, SAD-u i Aziji, i prihod od ~151 mil. EUR u 2025.\n\nNa papiru je to logičan potez. ASSA ABLOY već dominira bravama, cilindričnim mehanizmima i pristupnim kontrolama. Gunnebo dodaje fizičku barijeru na ulazu. Portfolio se zatvara u krug - nakon zatvaranja transakcije, Gunnebo ulazi u Pedestrian segment Entrance Systems divizije.\n\nFinansijski uslovi transakcije nisu objavljeni. Zatvaranje se očekuje u četvrtom kvartalu 2026, uz uobičajena regulatorna odobrenja.\n\n- Šta ovo znači za Balkan? -\nASSA ABLOY je prisutan u svim balkanskim zemljama - direktno ili kroz distributere. Svaka nova akvizicija znači širi katalog na jednoj adresi, ali i manje nezavisnih igrača u dobavljačkom lancu. Za projektante koji specificiraju ulazne sisteme za javne i poslovne objekte: portfolio koji vredi pratiti.",
    "read": "2 min",
    "source": "PR Newswire / ASSA ABLOY",
    "url": "https://www.prnewswire.com/news-releases/assa-abloy-to-acquire-gunnebo-entrance-control-302840968.html",
    "img": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-03T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-019",
    "cat": "standardi",
    "catLabel": "STANDARDI",
    "date": "avg 2026",
    "title": "ANSI Z97.1-2026: vakuumsko izolaciono staklo prvi put u standardu za sigurnosno staklo",
    "desc": "Nova revizija američkog standarda za sigurnosno staklo prvi put uključuje VIG (vacuum insulating glass) uz laminirano, kaljeno i ostalo sigurnosno staklo, i konsoliduje pet starih standarda za testiranje vremenskih uticaja u jedan. Signal industriji: VIG prestaje da bude nišni proizvod.",
    "body": "ASC Z97 komitet objavio je i akreditovao ANSI Z97.1-2026 - ažuriranu verziju američkog standarda za sigurnosno staklo u zgradama. Standard definiše specifikacije i metode testiranja za smanjenje rizika od posekotina i probijanja pri lomu stakla usled udara.\n\nNajveća novina: vakuumsko izolaciono staklo (VIG) je prvi put uključeno, uz laminirano, kaljeno, organsko-obloženo, plastično, ogledalsko i savijeno staklo. Standard definiše VIG kao sklop od najmanje dva sloja stakla, hermetički zatvorenog sa uskim, \"visoko evakuisanim\" prostorom koji drže distanceri.\n\nDodatno, pet odvojenih standarda za testiranje otpornosti na vremenske uticaje konsolidovano je u jednu zajedničku praksu - ASTM C1900. Dodat je i ASTM E903 kao alternativna metoda merenja propustljivosti vidljive svetlosti.\n\n- Šta ovo znači za Balkan? -\nNa Balkanu se VIG staklo tek uvodi kao rešenje za tanke, lagane sisteme (renovacije istorijskih fasada, gde debljina IGU jedinice nije opcija). Uključivanje VIG-a u vodeći američki standard je signal da tehnologija prelazi iz nišne u mejnstrim primenu - i da će je zapadnoevropski investitori sve češće tražiti u specifikacijama.",
    "read": "3 min",
    "source": "US Glass Magazine",
    "url": "https://www.usglassmag.com/ansi-releases-updated-z97-1-safety-glazing-standard/",
    "img": "https://images.unsplash.com/photo-1531973576160-7125cd663d86?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-08-01T12:00:00.000Z",
    "datumTacan": false,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-032",
    "cat": "investicije",
    "catLabel": "INVESTICIJA",
    "date": "avg 2026",
    "title": "Rollplast širi pogon u Kostinbrodu - solarni sistem od 4 MWp i pogled na Hrvatsku",
    "desc": "Bugarski Rollplast dobio je sertifikat klase A za proširenje pogona (~9,3 mil. EUR investicije, 30 novih radnih mesta), uz solarno-baterijski sistem od 4 MWp. Već imaju 140+ franšiznih partnera u regiji. Plan: ulazak na hrvatsko tržište.",
    "body": "Bugarski proizvođač aluminijumske i PVC stolarije Rollplast dobio je sertifikat investitora klase A za proširenje svog pogona u Kostinbrodu (pored Sofije) - investicija od oko 18,2 miliona leva (~9,3 mil. EUR) u novu proizvodnu halu, administrativnu zgradu i skladište gotovih proizvoda, sa 30 novih radnih mesta.\n\nDeo investicije je solarno-baterijski sistem snage 4 MWp, priključen na mrežu, uz dodatni baterijski sistem od 500 kW - deo šire strategije kompanije da smanji zavisnost od mrežne struje u energetski intenzivnoj proizvodnji profila.\n\nRollplast već ima preko 140 franšiznih partnera u regionu i proizvodi širok asortiman - aluminijumske i PVC prozore i vrata, roletne, ograde, tuš kabine. Ovo je jedna u nizu investicionih runda kompanije poslednjih godina (ranije runde uključivale su 9,3 mil. EUR i 15 mil. EUR ulaganja u proizvodnju).\n\n- Šta ovo znači za Balkan? -\nRollplast najavljuje širenje na hrvatsko tržište, što bi ga dovelo u direktnu konkurenciju sa lokalnim liderima poput Marlexa (sada u vlasništvu Inwido-a). Za srpske i regionalne distributere koji već sarađuju sa Rollplast franšiznom mrežom - jača proizvodna baza znači stabilniju isporuku i verovatno širi katalog u narednim sezonama.",
    "read": "2 min",
    "source": "SeeNews",
    "url": "https://seenews.com/news/interview-bulgarias-rollplast-building-4-mwp-solar-plus-battery-system-1223474",
    "img": "",
    "datumISO": "2026-08-01T12:00:00.000Z",
    "datumTacan": false,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-029",
    "cat": "proizvodi",
    "catLabel": "NOVI PROIZVOD",
    "date": "31. jul 2026",
    "title": "Strata i Vector: dva nova modela za tržište koje traži dizajn uz sigurnost",
    "desc": "Entrance širi Edge kolekciju - hibridna LVL konstrukcija, Inox detalji, 30 boja, PAS 24. Kompozitna vrata polako ulaze i na balkanska gradilišta.",
    "body": "Entrance Composite Door Solutions proširio je Edge kolekciju sa dva modela. Strata: čvrsta vrata sa osam letvica, čist dizajn sa vertikalnim senčenjem. Vector: četiri letvice sa ugrađenim Inox ostakljenjem i flush završetkom kroz kasete integrisane u krilo vrata.\n\nOba modela dolaze sa glatkim ili zrnatim GRP površinama u 30 boja i završnih obrada - standardne, premium, lakovane. Konstrukcija: LVL drveni okviri sa kompozitnim oblogama i sigurnosnim pločama. Oba su usklađena sa PAS 24.\n\n- Šta ovo znači za Balkan? -\nKompozitna vrata na Balkanu rastu sporije nego u zapadnoj Evropi, ali rastu. Kupci koji biraju ulazna vrata sve češće počinju sa pitanjem \"kako izgleda\" - i tek onda sa \"kakva je izolacija\". Uvoznici koji već sarađuju sa britanskim ili irskim dobavljačima: ovaj segment vredi pratiti u naredne dve do tri godine.",
    "read": "2 min",
    "source": "Window News UK",
    "url": "https://www.windownews.co.uk/entrance-composite-door-solutions-expands-edge-collection-with-strata-and-vector-doors/",
    "img": "",
    "datumISO": "2026-07-31T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-018",
    "cat": "kompanije",
    "catLabel": "AKVIZICIJA",
    "date": "9. jul 2026",
    "title": "Vytex kupuje Vinyl Kraft - konsoliduje proizvodnju PVC stolarije u SAD",
    "desc": "Vytex, proizvođač PVC zamenske stolarije sa sedištem u Merilendu, preuzeo je ohajski Vinyl Kraft. Prva akvizicija otkako je Vytex u vlasništvu Graycliff fonda - platforma se širi sa istočne obale na Srednji zapad.",
    "body": "Vytex, proizvođač PVC zamenske stolarije i patio vrata sa sedištem u Lorelu (Merilend), osnovan 1988. i sposoban da proizvede preko 200.000 prozora i vrata godišnje, preuzeo je Vinyl Kraft - proizvođača iz Nju Bostona (Ohajo) sa kapacitetom preko 100.000 jedinica godišnje.\n\nVinyl Kraft nastavlja da posluje samostalno, pod sopstvenim brendom, rukovodstvom i poslovnim modelom. Ovo je prva akvizicija Vytex-a otkako je kompanija u vlasništvu investicionog fonda Graycliff Partners - i prvi korak u širenju proizvodnog otiska sa istočne obale na Srednji zapad SAD-a.\n\n- Šta ovo znači za Balkan? -\nAmeričko tržište zamenske stolarije se konsoliduje po istom obrascu kao i evropsko - regionalni proizvođači se spajaju u veće platforme radi ekonomije obima. Za balkanske izvoznike koji prate globalne trendove konsolidacije: vredi znati ko su novi vlasnici i koje brendove drže, jer to menja i uslove nabavke sirovina i profila.",
    "read": "2 min",
    "source": "Graycliff Partners",
    "url": "https://graycliffpartners.com/news/vytex-vinyl-kraft",
    "img": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-07-09T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-027",
    "cat": "standardi",
    "catLabel": "TEHNIKA",
    "date": "jul 2026",
    "title": "ASSA ABLOY proširio testni centar na 691 m² - rezultati za dve nedelje",
    "desc": "UKAS-akreditovani centar u Daventriju (Britanija) testira PAS 24 pojačanu sigurnost za vratne sklopove, otpornost na koroziju i vodonepropusnost. Za balkanske proizvođače koji izvoze na UK tržište - relevantna adresa.",
    "body": "ASSA ABLOY je u Daventriju (Northamptonshire, UK) proširio UKAS-akreditovani test centar na 691 m². Centar posluje pod nazivom Heywood Williams Components Limited, trgujući kao \"ASSA ABLOY Test Centre\".\n\nŠta se može testirati: PAS 24 pojačana sigurnost za vratne sklopove, otpornost na koroziju i vodonepropusnost. Obećani turnaround za izveštaje i sertifikate: dve nedelje od uspešnog testiranja.\n\nLokacija je odabrana praktično - Daventri je čvor na M1, pristupačan iz svih pravaca UK, sa besplatnim parkingom i EV punjačima.\n\n- Šta ovo znači za Balkan? -\nZa proizvođače koji izvoze ili planiraju izvoz na UK tržište, PAS 24 sertifikacija je obavezna na velikom delu specifikacija. Ko sarađuje sa ASSA ABLOY-ovom mrežom u regionu - ovo je adresa za testiranje finalnih sklopova.",
    "read": "2 min",
    "source": "Window News UK",
    "url": "https://www.windownews.co.uk/assa-abloy-strengthens-uk-testing-offer-with-expanded-accredited-facility/",
    "img": "",
    "datumISO": "2026-07-01T12:00:00.000Z",
    "datumTacan": false,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-025",
    "cat": "trziste",
    "catLabel": "TRŽIŠTE",
    "date": "22. jun 2026",
    "title": "SAD: nova gradnja usporava, zamena raste. Šta to znači za nas?",
    "desc": "Mortgage Bankers Association u whitepaper-u tvrdi da priča o \"manjku stanova\" u SAD-u više ne stoji: ponuda bi mogla porasti za 10,6–14,6 miliona jedinica do 2035, dok je prosečna godišnja tražnja svega ~1,13 miliona. Formiranje domaćinstava pada.",
    "body": "Mortgage Bankers Association objavila je whitepaper koji kaže ono što mnogi nisu hteli da čuju: priča o \"manjku stanova\" u SAD-u više ne stoji. Prema proceni MBA, ponuda stanova mogla bi porasti za 10,6–14,6 miliona jedinica između 2026. i 2035, dok bi prosečna godišnja tražnja u istom periodu iznosila svega ~1,13 miliona jedinica - daleko ispod tempa potrebnog da apsorbuje tu ponudu.\n\nDemografija je pozadinska priča. Formiranje novih domaćinstava - koje MBA opisuje kao glavni pokretač dugoročne tražnje za stanovanjem - već je u padu: sa 2 miliona u 2021. na 1,1 milion u 2025. Do 2030, broj smrti u SAD-u premašiće broj rođenih.\n\nŠto to konkretno znači za stolarijsku industriju? Manje novih objekata, više zamene i renovacije. Model prihoda se pomera - iz \"prodaj jedanput graditelju\" u \"prodaj više puta krajnjem korisniku koji menja stolariju staru 15 godina\".\n\n- Šta ovo znači za Balkan? -\nSrbija, Crna Gora i Severna Makedonija su još uvek u fazi rasta nove gradnje - pa se ovo ne tiče nas neposredno. Ali tržišta koja su prolazila kroz istu tranziciju uvek su je prolazila sa faznim pomakom. Kompanije koje sad grade retrofit i zamenski kanal biće u poziciji kad trend stigne ovamo.",
    "read": "4 min",
    "source": "Mortgage Bankers Association",
    "url": "https://www.mba.org/news-and-research/newsroom/news/2026/06/22/mba-white-paper--demographic-trends-could-reshape-future-housing-demand",
    "img": "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-06-22T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-022",
    "cat": "tehnologija",
    "catLabel": "TEHNOLOGIJA",
    "date": "27. maj 2026",
    "title": "MACO Sense: dva evropska priznanja za pametni okov u jednoj godini",
    "desc": "Nakon Red Dot Awarda za dizajn, sada i German Innovation Award u zlatnoj kategoriji. MACO-ov senzorski okov koji prati status prozora i vrata i radi na Matter protokolu postaje standard na koji se industrija poziva.",
    "body": "Berlinska ceremonija German Innovation Award donela je MACO-u zlatnu nagradu u kategoriji \"Excellence in Business to Business – Building & Elements\". Ranije te godine, Sense by MACO je već osvojio Red Dot Award za dizajn proizvoda 2026 - pobedivši konkurenciju iz više od 60 zemalja.\n\nSense je, ukratko, okov koji pamti. Integrisani senzori prate status prozora, kliznih i ulaznih vrata i komuniciraju sa pametnom zgradom. Pet varijanti pokriva sve tipove - Window Pro T&T, Window T&T, Casement, Door i Universal. Sve rade na Matter protokolu, što znači da se bez problema integrišu sa uređajima različitih proizvođača.\n\nZašto je to važno: integrator koji gradi pametnu zgradu ne želi da mu okov \"ne priča\" sa termostatom ili alarmom. Matter protokol to rešava. MACO je to prepoznao rano - i sad bere nagrade.\n\n- Šta ovo znači za Balkan? -\nMACO je verovatno najzastupljeniji dobavljač okova u regionu. Sense serija dostupna je kod ovlašćenih distributera u Srbiji, BiH i Hrvatskoj. Ko god pravi prozore ili vrata za pametne zgrade - ili želi da uđe u taj segment - treba da zna za ovu seriju.",
    "read": "3 min",
    "source": "MACO",
    "url": "https://www.maco.eu/en-INT/News/Sense-by-MACO-wins-two-awards",
    "img": "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=900&fit=crop&auto=format&q=75",
    "datumISO": "2026-05-27T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-031",
    "cat": "kompanije",
    "catLabel": "AKVIZICIJA",
    "date": "maj 2026",
    "title": "Inwido kupuje Marlex - Šveđani ušli na hrvatsko tržište",
    "desc": "Inwido, najveći proizvođač prozora i vrata u Evropi, platio je 5,1–6,3x EBITDA za 70% udela u varaždinskom Marlexu. 270 zaposlenih, prihod ~33 mil. EUR, vlastita IGU produkcija - lider PVC prozora u Hrvatskoj.",
    "body": "Švedski Inwido, najveći proizvođač prozora i vrata u Evropi po prihodu, dogovorio je otkup 70% udela u hrvatskom Marlexu iz Varaždina - svoj prvi ulazak na hrvatsko tržište i deo šire strategije širenja u istočnoj Evropi.\n\nMarlex je osnovan 2003. i danas se smatra tržišnim liderom u proizvodnji PVC prozora u Hrvatskoj: oko 270 zaposlenih, godišnji prihod od približno 33 miliona EUR, i sopstvena proizvodnja IGU (izolacionih staklenih jedinica) - što znači vertikalnu integraciju koja retko postoji kod regionalnih proizvođača te veličine.\n\nTransakcija vrednuje većinski udeo po multiplikatoru 5,1–6,3x EBITDA na osnovu rezultata iz 2025, sa opcijom (call/put) da Inwido otkupi preostalih 30% u 2028. Zatvaranje transakcije očekivano je u junu 2026.\n\n- Šta ovo znači za Balkan? -\nInwido gradi regionalnu mrežu akvizicijama, ne organskim rastom - ovo je obrazac koji se ponavlja širom istočne Evrope. Za hrvatske i regionalne konkurente Marlexa, to znači novog igrača sa pristupom skandinavskom kapitalu i distribucijom, sposobnog da agresivnije investira u kapacitet i marketing nego pre akvizicije.",
    "read": "3 min",
    "source": "Inwido",
    "url": "https://www.inwido.com/pressreleases/inwido-enters-the-croatian-market-through-the-acquisition-of-marlex-movfp31d-2b7a0",
    "img": "",
    "datumISO": "2026-05-01T12:00:00.000Z",
    "datumTacan": false,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-028",
    "cat": "tehnologija",
    "catLabel": "MARKETING",
    "date": "25. mar 2026",
    "title": "Hörmann Truedor: kako kompanija gradi mrežu dilera kroz roadshow i TV kampanju",
    "desc": "Jutarnji događaji za instalatere, kampanja na društvenim mrežama u stilu sapunica, Installer Finder koji preusmerava kupce lokalnim dilerima. Model koji funkcioniše i van Britanije.",
    "body": "Hörmann Truedor je pokrenuo seriju roadshow događaja po UK-u namenjenih instalaterima kompozitnih vrata - jutarnji formati, kafa, doručak, razgovor o tome kako proširiti portfolio i zaraditi više po ugrađenim vratima.\n\nUz roadshow, kompanija je lansirala i \"Hörmann Street\" - kampanju na društvenim mrežama inspirisanu britanskim sapunicama, sa fiktivnom ulicom i likovima koji se ponavljaju u svakodnevnim scenarijima gde se vrata prirodno pojavljuju.\n\nInstalaterima koji su prisustvovali ponuđeni su: 1.500 funti vaučera za vrata, 750 bonus bodova u Hörmann Rewards programu i godišnji besplatan pristup Door Designer alatu. Upiti sa nove veb stranice preusmeravaju se lokalnim odobrenim dilerima kroz Installer Finder.\n\n- Šta ovo znači za Balkan? -\nHörmann je aktivan u celoj jugoistočnoj Evropi. Ovaj model - centralna kampanja plus lokalna distribucija upita - funkcioniše i van UK. Regionalni distributeri koji grade dilersku mrežu mogu preuzeti istu logiku.",
    "read": "3 min",
    "source": "Pro Installer",
    "url": "https://www.proinstaller.co.uk/2026/03/25/hormann-truedor-roadshows-putting-installers-first/",
    "img": "",
    "datumISO": "2026-03-25T12:00:00.000Z",
    "datumTacan": true,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-033",
    "cat": "kompanije",
    "catLabel": "JUBILEJ",
    "date": "2026",
    "title": "Alumil slavi 20 godina fabrike u Srbiji",
    "desc": "Grčka Alumil grupacija obeležava dve decenije ekstruzije aluminijumskih profila u Čačku. Jedna od retkih vlastitih ekstruzija u regionu - i dokaz da se na Balkanu može praviti aluminijum koji ide na zahtevna tržišta.",
    "body": "Grčka grupacija Alumil obeležava 20 godina rada svoje fabrike u Čačku - Alumil YU Industry, koja radi sopstvenu ekstruziju aluminijumskih profila za arhitektonske, prozorske i fasadne sisteme.\n\nČinjenica da fabrika u Čačku radi vlastitu ekstruziju, a ne samo završnu obradu uvezenih profila, izdvaja je od većine regionalnih igrača koji uvoze gotove profile i rade samo sečenje, bušenje i sklapanje. Vlastita ekstruzija znači kraće rokove isporuke, veću kontrolu kvaliteta i mogućnost da se profili prilagode specifičnim zahtevima kupaca umesto da se biraju sa gotove liste.\n\nDve decenije neprekidnog rada u istom pogonu, u industriji gde su zatvaranja i konsolidacije (kao kod Owens Corning ili u sektoru kompozitnih vrata) postali uobičajeni, samo po sebi je vredno pažnje.\n\n- Šta ovo znači za Balkan? -\nAlumil Čačak je dokaz da lokalna, vlasnički stabilna proizvodnja aluminijumskih profila u regionu može opstati i rasti dve decenije, uprkos konkurenciji uvoznih profila i globalnoj konsolidaciji industrije. Za fabrikante koji biraju dobavljača profila, lokalna ekstruzija znači brže reagovanje na hitne narudžbe i manju izloženost prekidima u međunarodnim lancima snabdevanja.",
    "read": "2 min",
    "source": "Alumil",
    "url": "https://www.alumil.com/serbia",
    "img": "",
    "datumISO": "2026-01-01T12:00:00.000Z",
    "datumTacan": false,
    "status": "objavljeno",
    "poreklo": "arhiva"
  },
  {
    "id": "arh-034",
    "cat": "kompanije",
    "catLabel": "INVESTICIJA",
    "date": "2026",
    "title": "Yavuz Company BiH: domaći proizvođač PVC profila sa tri fabrike",
    "desc": "Jedini domaći proizvođač PVC profila u BiH radi stotine otvora dnevno iz tri fabrike, sa sistemima BAUWIN i BAUFENS i izvozom u Evropu i Afriku. Priča o kompaniji koja je vertikalu izgradila u Bosni od nule.",
    "body": "Yavuz Company je, prema sopstvenim navodima, jedini domaći proizvođač PVC profila u Bosni i Hercegovini - pozicija koja je retka u regionu gde većina fabrikanata uvozi gotove profile od velikih evropskih sistema (Veka, Rehau, Aluplast, Deceuninck) i radi samo sklapanje.\n\nKompanija posluje kroz tri fabrike i nudi sopstvene profilne sisteme pod imenima BAUWIN i BAUFENS, uz izvoz gotove stolarije i profila u Evropu i Afriku. Ova vertikalna integracija - od proizvodnje profila do gotovih prozora i vrata - izgrađena je u Bosni tokom dve decenije, bez strane matične kompanije iza sebe.\n\nZa tržište BiH, gde su javne nabavke stolarije (poput one u Sarajevu i Banjoj Luci koje redakcija prati u sekciji Tenderi) često osetljive na cenu i rok isporuke, domaći proizvođač profila ima strukturnu prednost - kraći lanac snabdevanja i manju izloženost kursnim rizicima uvoza.\n\n- Šta ovo znači za Balkan? -\nYavuz je primer da se u BiH može izgraditi kompletna vertikala od profila do gotovog proizvoda, bez oslanjanja na velike zapadnoevropske sisteme. Za investitore i javne naručioce u regionu koji traže alternativu uvoznim profilima - posebno tamo gde brzina isporuke ili domaći sadržaj igraju ulogu u odabiru ponude - ovo je dobavljač vredan pažnje.",
    "read": "3 min",
    "source": "Yavuz.ba",
    "url": "https://www.yavuz.ba",
    "img": "",
    "datumISO": "2026-01-01T12:00:00.000Z",
    "datumTacan": false,
    "status": "objavljeno",
    "poreklo": "arhiva"
  }
];
